# =============================================================================
# NESTSECURE - Módulo de Utilidades
# =============================================================================
"""
Utilidades y helpers para toda la aplicación.

Módulos:
- logger: Sistema de logging estructurado
- constants: Constantes y enums del sistema
- helpers: Funciones helper comunes
- validators: Validadores personalizados
"""

from .constants import (
    AssetCriticality,
    AssetType,
    CommonPorts,
    ErrorCode,
    HTTP_STATUS_MESSAGES,
    PaginationLimits,
    Patterns,
    RateLimits,
    ROLE_HIERARCHY,
    ScanStatus,
    ScanType,
    Timeouts,
    UserRole,
    VulnerabilitySeverity,
)
from .helpers import (
    bytes_to_human,
    datetime_to_timestamp,
    expand_cidr,
    expand_port_range,
    flatten_dict,
    format_duration,
    generate_api_key,
    generate_checksum,
    generate_short_id,
    generate_token,
    generate_uuid,
    generate_uuid_str,
    get_ip_version,
    hash_string,
    is_private_ip,
    is_valid_cidr,
    is_valid_ip,
    is_valid_ipv4,
    is_valid_ipv6,
    is_valid_port,
    is_valid_port_range,
    mask_string,
    safe_float,
    safe_int,
    sanitize_string,
    slugify,
    time_ago,
    timestamp_to_datetime,
    truncate,
    utc_now,
)
from .logger import (
    clear_context,
    get_logger,
    log_execution,
    set_request_context,
    set_task_context,
    setup_logging,
)
from .validators import (
    CIDRNetwork,
    CVEId,
    IPAddress,
    IPv4Address,
    IPv6Address,
    Port,
    Slug,
    create_length_validator,
    create_regex_validator,
    validate_cidr,
    validate_cpe,
    validate_cve_id,
    validate_cvss_score,
    validate_fqdn,
    validate_hostname,
    validate_in_list,
    validate_ip_address,
    validate_ip_or_cidr,
    validate_ipv4,
    validate_ipv6,
    validate_length,
    validate_mac_address,
    validate_not_empty,
    validate_password_strength,
    validate_port,
    validate_port_list,
    validate_port_range,
    validate_regex,
    validate_slug,
    validate_uuid,
)

__all__ = [
    # Constants
    "ErrorCode",
    "PaginationLimits",
    "Timeouts",
    "RateLimits",
    "VulnerabilitySeverity",
    "ScanStatus",
    "ScanType",
    "AssetType",
    "AssetCriticality",
    "UserRole",
    "ROLE_HIERARCHY",
    "Patterns",
    "CommonPorts",
    "HTTP_STATUS_MESSAGES",
    # Logger
    "get_logger",
    "setup_logging",
    "set_request_context",
    "set_task_context",
    "clear_context",
    "log_execution",
    # Helpers
    "generate_uuid",
    "generate_uuid_str",
    "generate_short_id",
    "generate_token",
    "generate_api_key",
    "hash_string",
    "generate_checksum",
    "is_valid_ipv4",
    "is_valid_ipv6",
    "is_valid_ip",
    "is_valid_cidr",
    "is_private_ip",
    "is_valid_port",
    "is_valid_port_range",
    "expand_cidr",
    "expand_port_range",
    "get_ip_version",
    "sanitize_string",
    "slugify",
    "truncate",
    "mask_string",
    "utc_now",
    "timestamp_to_datetime",
    "datetime_to_timestamp",
    "format_duration",
    "time_ago",
    "bytes_to_human",
    "safe_int",
    "safe_float",
    "flatten_dict",
    # Validators
    "validate_ipv4",
    "validate_ipv6",
    "validate_ip_address",
    "validate_cidr",
    "validate_ip_or_cidr",
    "validate_port",
    "validate_port_range",
    "validate_port_list",
    "validate_mac_address",
    "validate_hostname",
    "validate_fqdn",
    "validate_slug",
    "validate_uuid",
    "validate_cve_id",
    "validate_cpe",
    "validate_cvss_score",
    "validate_not_empty",
    "validate_length",
    "validate_regex",
    "validate_in_list",
    "validate_password_strength",
    # Pydantic Types
    "IPv4Address",
    "IPv6Address",
    "IPAddress",
    "CIDRNetwork",
    "Port",
    "CVEId",
    "Slug",
    # Factories
    "create_length_validator",
    "create_regex_validator",
]
