"""add_scans_vulnerabilities_cve_cache

Revision ID: 0680cdb4620c
Revises: dd3d510b7aa4
Create Date: 2026-01-30 15:06:21.695568+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0680cdb4620c'
down_revision = 'dd3d510b7aa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_cache',
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('published_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cvss_v3_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=200), nullable=True),
    sa.Column('cvss_v3_severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_attack_vector', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_attack_complexity', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_privileges_required', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_user_interaction', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_scope', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_confidentiality_impact', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_integrity_impact', sa.String(length=20), nullable=True),
    sa.Column('cvss_v3_availability_impact', sa.String(length=20), nullable=True),
    sa.Column('cvss_v2_score', sa.Float(), nullable=True),
    sa.Column('cvss_v2_vector', sa.String(length=200), nullable=True),
    sa.Column('cvss_v2_severity', sa.String(length=20), nullable=True),
    sa.Column('affected_cpes', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('affected_vendors', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('affected_products', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('exploit_code_maturity', sa.String(length=50), nullable=True),
    sa.Column('exploit_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('epss_score', sa.Float(), nullable=True),
    sa.Column('epss_percentile', sa.Float(), nullable=True),
    sa.Column('epss_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_cisa_kev', sa.Boolean(), nullable=False),
    sa.Column('cisa_date_added', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cisa_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cisa_required_action', sa.Text(), nullable=True),
    sa.Column('cisa_vulnerability_name', sa.String(length=500), nullable=True),
    sa.Column('cwe_ids', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_source', sa.String(length=50), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('cve_id', name=op.f('pk_cve_cache'))
    )
    op.create_index(op.f('ix_cve_cache_in_cisa_kev'), 'cve_cache', ['in_cisa_kev'], unique=False)
    
    op.create_table('scans',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('targets', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('excluded_targets', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('port_range', sa.String(length=500), nullable=True),
    sa.Column('engine_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=100), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('total_hosts_scanned', sa.Integer(), nullable=False),
    sa.Column('total_hosts_up', sa.Integer(), nullable=False),
    sa.Column('total_services_found', sa.Integer(), nullable=False),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('vuln_critical', sa.Integer(), nullable=False),
    sa.Column('vuln_high', sa.Integer(), nullable=False),
    sa.Column('vuln_medium', sa.Integer(), nullable=False),
    sa.Column('vuln_low', sa.Integer(), nullable=False),
    sa.Column('vuln_info', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_by_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_scans_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scans_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_organization_id'), 'scans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    
    op.create_table('vulnerabilities',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('asset_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('service_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('scan_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('references', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('cwe_id', sa.String(length=20), nullable=True),
    sa.Column('cwe_name', sa.String(length=255), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exploit_available', sa.Boolean(), nullable=False),
    sa.Column('exploit_maturity', sa.String(length=50), nullable=True),
    sa.Column('in_the_wild', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('times_detected', sa.Integer(), nullable=False),
    sa.Column('scanner_name', sa.String(length=100), nullable=True),
    sa.Column('scanner_plugin_id', sa.String(length=100), nullable=True),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_vulnerabilities_asset_id_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_vulnerabilities_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cve_id'], ['cve_cache.cve_id'], name=op.f('fk_vulnerabilities_cve_id_cve_cache'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_vulnerabilities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_vulnerabilities_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_vulnerabilities_scan_id_scans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_vulnerabilities_service_id_services'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerabilities'))
    )
    op.create_index(op.f('ix_vulnerabilities_asset_id'), 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cvss_score'), 'vulnerabilities', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_exploit_available'), 'vulnerabilities', ['exploit_available'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_organization_id'), 'vulnerabilities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_risk_score'), 'vulnerabilities', ['risk_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_scan_id'), 'vulnerabilities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_service_id'), 'vulnerabilities', ['service_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_status'), 'vulnerabilities', ['status'], unique=False)
    
    op.create_table('vulnerability_comments',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('vulnerability_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vulnerability_comments_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], name=op.f('fk_vulnerability_comments_vulnerability_id_vulnerabilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vulnerability_comments'))
    )
    op.create_index(op.f('ix_vulnerability_comments_user_id'), 'vulnerability_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_comments_vulnerability_id'), 'vulnerability_comments', ['vulnerability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerability_comments_vulnerability_id'), table_name='vulnerability_comments')
    op.drop_index(op.f('ix_vulnerability_comments_user_id'), table_name='vulnerability_comments')
    op.drop_table('vulnerability_comments')
    op.drop_index(op.f('ix_vulnerabilities_status'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_service_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_scan_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_risk_score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_organization_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_exploit_available'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cvss_score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_asset_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_organization_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_cve_cache_in_cisa_kev'), table_name='cve_cache')
    op.drop_table('cve_cache')
    # ### end Alembic commands ###
