"""add_host_port_to_vulnerabilities

Revision ID: 4c582262c53d
Revises: 0680cdb4620c
Create Date: 2026-02-05 18:17:36.218330+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c582262c53d'
down_revision = '0680cdb4620c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'gvm_target_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID del target en GVM',
               existing_nullable=True)
    op.alter_column('scans', 'gvm_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID de la task en GVM',
               existing_nullable=True)
    op.alter_column('scans', 'gvm_report_id',
               existing_type=sa.VARCHAR(length=255),
               comment='UUID del report en GVM',
               existing_nullable=True)
    op.add_column('vulnerabilities', sa.Column('host', sa.String(length=255), nullable=True))
    op.add_column('vulnerabilities', sa.Column('port', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'port')
    op.drop_column('vulnerabilities', 'host')
    op.alter_column('scans', 'gvm_report_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID del report en GVM',
               existing_nullable=True)
    op.alter_column('scans', 'gvm_task_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID de la task en GVM',
               existing_nullable=True)
    op.alter_column('scans', 'gvm_target_id',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='UUID del target en GVM',
               existing_nullable=True)
    # ### end Alembic commands ###
