"""Initial tables: organizations users assets services

Revision ID: dd3d510b7aa4
Revises: 32be6e140ffc
Create Date: 2026-01-29 13:34:34.551116+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3d510b7aa4'
down_revision = '32be6e140ffc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
